# ===========================================================================================
# Thank you for using the Minestore system by Liel Amar.
# For support, you can contact us through my discord server: https://discord.gg/NzgBrqR.
#
# Github: https://github.com/LielAmar/Minestore
# ===========================================================================================

# Whether to notify when there's an update available
Check For Updates: true

# Using Bungeecord
Using Bungeecord: false

# Your MySQL Database Credentials to check transactions.
# This should be the same as the credentials in your website!
MySQL:
  credentials:
    host: "localhost"
    database: "minestore"
    port: 3306

    auth:
      username: "admin"
      password: "userpassword"

# IP of your Web Server
Allowed Connection IP: "localhost"

# Your In-game Server information
Socket Server:
  port: 1804